# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c3806d814b86ec2468015c0e6c4155159e8fc62bbd6535f59edf3017eec347c704c2dfc3eb64af2934cd3b941ac23439f4f948d405e984797ca35b4bcbe3ad17

test:
  secret_key_base: 19d65e4e95a2e6a519a4e0d653ab3bced29314c52a1887afe4fa8b7249df90c8bcb71ecad779aa23b38ae235f7a629cbb43f954f1054eb15b42231cbc41ef80f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
